
services:
  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile.dev
    container_name: backend-test
    networks:
      - fpart-net
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: #config path

  frontend:
    build:
      context: ../Frontend
    container_name: frontend-test
    networks:
      - fpart-net
    ports:
      - "5173:5173"
    volumes:
      - ../Frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  database:
    image: postgres:15-alpine
    container_name: postgres-database-test
    networks:
      - fpart-net
    ports:
      - "5432:5432"
    volumes:
      - ../Backend/migrations/.initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fpart
      # DSN for copy: postgres://postgres:password@localhost:5432/fpart?sslmode=disable


networks:
  fpart-net:
    driver: bridge